### DISCUSSION TITLE
Drop Down height

### DISCUSSION THREAD

**Discussion by saschagysel** [orchidjs/tom-select#487] [Q&A]
How can I change the height of the selection drop down so there is more options being shown? I did not find it in the docs nor in this forum.

**Comment by saschagysel** [comment]
Anyone who can help here?

**Comment by Vinze** [comment]
This can be accomplished with some css:

```css
.ts-dropdown-content {
    max-height: 200px; /* change this */
}
```
