### DISCUSSION TITLE
Dropdown caret default theme

### DISCUSSION THREAD

**Discussion by Vinze** [orchidjs/tom-select#516] [Ideas]
The default theme doesn't have a dropdown caret/angle/arrow. For my own project I solved it with a little bit of css. Maybe this would be a nice addition to include in the default theme?

![angle updown](https://user-images.githubusercontent.com/1716574/199941719-82adc9ab-23de-4c47-8284-af97f22b4b87.gif)

```css
.ts-wrapper {
    position: relative;
}
.ts-control::after {
    position: absolute;
    top: 0.5rem;
    right: 0.25rem;
    content: '›';
    font-size: 24px;
    transform: rotate(90deg);
    line-height: 20px;
    width: 20px;
    height: 20px;
    text-align: center;
    transition: transform .1s;
}
.dropdown-active .ts-control::after {
    transform: scaleY(-1) rotate(90deg);
}
```
