### ISSUE TITLE
Tom Select problems with Bootstrap 5 table responsive and/or modal

### ISSUE THREAD

**Issue by artur79** [orchidjs/tom-select#557]
When using Tom Select inside <td> in BS5 .table-responsive, opened dropdown is mostly hidden. I'v managed to overcome that issue by using ```dropdownParent: 'body'``` config option.

But when .table-responsive is located inside boostrap modal, I'v got similar but not identical issue, <td> becomes extended with dropdown, instead dropdown to appear over modal. Any ideas how to resolve it with dropdownParent maybe somehow or some css ?

**Comment by matthewdfuller** [comment]
This is an old issue, but I semi-solved this by adding a CSS rule to my stylesheet:

```
.ts-dropdown {
  z-index: 10000000 !important;
}
```

**Comment by gumbarros** [comment]
I solved the problem definitively using the following CSS:

```css
.table-responsive:has(.ts-wrapper.dropdown-active) {
    overflow: visible !important;
}

.table-responsive .ts-dropdown {
    z-index: 1080;
}
```
