### ISSUE TITLE
It doesnt work with floating inputs

### ISSUE THREAD

**Issue by hightowertech** [orchidjs/tom-select#579]
**Describe the bug**
Bootstrap 5 has floating inputs, tomselect doesnt seem to recognize them.

**To Reproduce**
Create an example on JSFiddle, CodePen or similar service and outline the steps for reproducing the bug.
1) use the tomselect bootstrap 5 css
2) make a form-floating select tag https://getbootstrap.com/docs/5.3/forms/floating-labels/#example

**Expected behavior**
at least look like a floating label
https://i.imgur.com/d2m67Ht.png
^look like the select on the right side [im working on this now but i may abandon it]

<!--
Thanks for taking the time to submit your bug report,
and don't forget to star our repo!

**Comment by hightowertech** [comment]
`
.ts-wrapper.form-control, .ts-wrapper.form-select {
	height:calc(3.5rem + calc(var(--bs-border-width) * 2));
    font-size: 12px;
    margin: 0 25px 0 0;

	line-height:1.25;
}

.ts-control{
	padding: 0rem 0.25rem;
		padding-top: 1.5rem!important;
    padding-bottom: 0.625rem!important;
}
`
tbh this is working great

**Comment by hightowertech** [comment]
```
.ts-wrapper.form-control, .ts-wrapper.form-select {
	height:calc(3.5rem + calc(var(--bs-border-width) * 2));
    font-size: 12px;
    margin: 0 25px 0 0;

	line-height:1.25;
}

.ts-control{
	padding: 0rem 0.25rem;
		padding-top: 1.5rem!important;
    padding-bottom: 0.625rem!important;
}
```
this fixes it for me so far [windows10 > chrome]

**Comment by oyejorge** [comment]
It would be nice! Feel free to submit a pull request with an implementation.

**Comment by silent-e** [comment]
Anyone figured out how to get the label to actually shift position based on the :placeholder-shown status like Bootstrap does?

**Comment by Nexotap** [comment]
I can confirm @AgentSmith0 solution. I'm absolutely bad in creating PR's else I would have made one. Would be happy seeing this implemented in near future.

**Comment by pigoz** [comment]
```css
.form-floating {
  /* move ts-control input element below the floating label */
  .ts-wrapper.form-control,
  .ts-wrapper.form-select {
    height: 0 !important;
  }

  .ts-wrapper.form-control .ts-control,
  .ts-wrapper.form-select .ts-control {
    padding-top: 1.625rem;
    padding-bottom: 0.625rem;
  }

  /* if field is styled as a text field (.form-control instead of .form-select)
   * make sure we apply the same animation as Bootstrap 5 */
  .ts-wrapper.form-control ~ label,
  .ts-wrapper.form-select ~ label {
    transform: scale(1) translateY(0) translateX(0);
    color: rgba(var(--bs-body-color-rgb), 1);
  }

  .ts-wrapper.form-control.focus ~ label,
  .ts-wrapper.form-control.full ~ label,
  .ts-wrapper.form-select.focus ~ label,
  .ts-wrapper.form-select.full ~ label,
  .ts-wrapper.form-select.has-items ~ label {
    transform: scale(0.85) translateY(-0.5rem) translateX(0.15rem);
    color: rgba(var(--bs-body-color-rgb), 0.65);
  }

  /* hides empty value which tomselect uses as placeholder */
  .ts-wrapper.form-select:not(.focus) .ts-control ::placeholder {
    opacity: 0;
  }
}
```

@silent-e This adds the animation similar to other Bootstrap components
