### ISSUE TITLE
Bootstrap theme doesn't respect Bootstrap color schema

### ISSUE THREAD

**Issue by Kolyunya** [orchidjs/tom-select#634]
**Describe the bug**
Bootstrap theme doesn't respect Bootstrap color schema.

**To Reproduce**
1. Go to https://jsfiddle.net/Kolyunya/L4u8xptg/2/
2. See theme background color is black.
3. See Bootstrap select background is black.
4. See Tom Select select background is white.

**Expected behavior**
Select background color and text color should match the Bootstrap theme.

**Additional context**
 - OS: MacOS v13
 - Device: Mac Book
 - Browser Chrome v116, Firefox v117

<img width="724" alt="Screenshot 2023-09-25 at 20 26 01" src="https://github.com/orchidjs/tom-select/assets/2682768/ab366c1c-a5f9-471d-9392-b3b7e0268ea0">

**Comment by crivotz** [comment]
I temporarily fixed the problem with the following scss

```scss
/* TOM SELECT */
.ts-dropdown, .ts-control, .ts-control input {
  color: var(--bs-body-color);
}
.ts-wrapper.plugin-remove_button .item .remove {
  color: $red;
}
.plugin-clear_button .clear-button {
  color: $red;
  right: 60px;
}
.ts-dropdown {
  z-index: 1060;
}
```
