### ISSUE TITLE
Height on narrow selects is too tall

### ISSUE THREAD

**Issue by danstewart** [orchidjs/tom-select#85]
**Describe the bug**
Inner input is visible for narrow selects, even with a default value.

**To Reproduce**
1. Create a `select` with a width a bit bigger than the contents

Here is a JSFiddle showing the issue:
https://jsfiddle.net/3yjzwhaq/

**Expected behavior**
Input should be hidden if a value is set.
It looks like when manually selecting a value the input is given the following styles:
```css
style="opacity: 0; position: absolute; left: -10000px;"
```

**Additional context**
 - OS: [Ubuntu 20.04]
 - Browser [Firefox]
 - Version [88.0.1]
 - Device: [Desktop]

Tested with same result on Chromium 90.0.4430.212

---

Manually setting the style is a good workaround:
```
document.querySelector('#my-select-tomselected').style = "opacity: 0; position: absolute; left: -10000px"
```

<!--
Thanks for taking the time to submit your bug report,
anbd don't forget to star our repo!

**Comment by oyejorge** [comment]
[Here's a CSS only workaround as well](https://jsfiddle.net/sah4w0ju/1/)

```css
.input-hidden > .ts-input > input{
  display:none !important;
}
```

**Comment by oyejorge** [comment]
Thanks! I'll have an updated release out shortly

**Comment by danstewart** [comment]
Nice one, thanks a lot!

**Comment by iazaran** [comment]
This one can hide it just if it has value:
```css
.ts-input.has-items > input {
    display: none !important;
}
```

**Comment by danstewart** [comment]
Workaround for V2:
```css
.ts-wrapper.has-items > .ts-control > input {
    position: absolute !important;
    left: -1000px !important;
    opacity: 1 !important;
}
```
